name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create Self Contained App
      run: dotnet publish -p:PublishProfile=FolderProfile
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Stop service
    - uses: garygrossgarten/github-action-ssh@release
      with:
            command: systemctl stop WaitingListBot
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            privateKey: ${{ secrets.PRIVATE_KEY }}
    - name: Start service
    - uses: garygrossgarten/github-action-ssh@release
      with:
            command: systemctl start WaitingListBot
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            privateKey: ${{ secrets.PRIVATE_KEY }}
