name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create Self Contained App
      run: dotnet publish -p:PublishProfile=FolderProfile -c Release
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
          name: waitinglistbot
          path: WaitingListBot/bin/Release/net5.0/linux-x64/
    - name: Save web artifact
      uses: actions/upload-artifact@v2
      with:
          name: waitinglistbotweb
          path: WaitingListBot.Web/bin/Release/net5.0/linux-x64/
    
  # deploy:
  #   if: ${{ github.event_name == 'push' }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #         name: waitinglistbot
  #   - name: Copy artifacts
  #     uses: appleboy/scp-action@master
  #     with:
  #       source: "."
  #       target: "/var/waitinglistbot/"
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key : ${{ secrets.PRIVATE_KEY }}
  #   - name: Mark executable
  #     uses: garygrossgarten/github-action-ssh@release
  #     with:
  #           command: chmod +x /var/waitinglistbot/WaitingListBot
  #           host: ${{ secrets.HOST }}
  #           username: ${{ secrets.USERNAME }}
  #           privateKey: ${{ secrets.PRIVATE_KEY }}
  #   - name: Restart service
  #     uses: garygrossgarten/github-action-ssh@release
  #     with:
  #           command: sudo systemctl restart WaitingListBot
  #           host: ${{ secrets.HOST }}
  #           username: ${{ secrets.USERNAME }}
  #           privateKey: ${{ secrets.PRIVATE_KEY }}
  # deployweb:
  #   if: ${{ github.event_name == 'push' }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #         name: waitinglistbotweb
  #   - name: Copy artifacts
  #     uses: appleboy/scp-action@master
  #     with:
  #       source: "."
  #       target: "/var/waitinglistbotweb/"
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key : ${{ secrets.PRIVATE_KEY }}
  #   - name: Start service
  #     uses: garygrossgarten/github-action-ssh@release
  #     with:
  #           command: sudo systemctl restart waitinglistbotweb
  #           host: ${{ secrets.HOST }}
  #           username: ${{ secrets.USERNAME }}
  #           privateKey: ${{ secrets.PRIVATE_KEY }}
